In [1]:
import numpy as np

In [2]:
# Range can only generate integers
l = list(range(10))

In [3]:
# If we need to generate floats use np.arange()
np.arange(.4,10,step=0.10)

array([0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6,
       1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9,
       3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2,
       4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5,
       5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8,
       6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1,
       8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4,
       9.5, 9.6, 9.7, 9.8, 9.9])

In [4]:
# Return evenly spaced numbers over a specified interval. -> used to generate data 
np.linspace(1,3,num=25)

array([1.        , 1.08333333, 1.16666667, 1.25      , 1.33333333,
       1.41666667, 1.5       , 1.58333333, 1.66666667, 1.75      ,
       1.83333333, 1.91666667, 2.        , 2.08333333, 2.16666667,
       2.25      , 2.33333333, 2.41666667, 2.5       , 2.58333333,
       2.66666667, 2.75      , 2.83333333, 2.91666667, 3.        ])

In [5]:
# Return numbers spaced evenly on a log scale.
np.logspace(1,3,num=20)

array([  10.        ,   12.74274986,   16.23776739,   20.69138081,
         26.36650899,   33.59818286,   42.81332399,   54.55594781,
         69.51927962,   88.58667904,  112.88378917,  143.84498883,
        183.29807108,  233.57214691,  297.63514416,  379.26901907,
        483.29302386,  615.84821107,  784.75997035, 1000.        ])

In [6]:
np.zeros(4)

array([0., 0., 0., 0.])

In [7]:
np.zeros(shape=(3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.zeros(shape=(2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
arr_4d =np.zeros(shape=(2,2,3,3))

In [10]:
arr_4d

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [11]:
arr_4d.ndim


4

In [12]:
arr_4d.shape

(2, 2, 3, 3)

In [13]:
arr_4d.size

36

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
ones_1 = np.ones((2,3))

In [16]:
ones_1 +3 

array([[4., 4., 4.],
       [4., 4., 4.]])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
import pandas as pd

In [20]:
pd.DataFrame(ones_1)

0    1    2
0  1.0  1.0  1.0
1  1.0  1.0  1.0

In [21]:
# Random values in a given shape.
np.random.rand(3,4)

array([[0.52765816, 0.67536102, 0.80542804, 0.7328401 ],
       [0.4311499 , 0.28965885, 0.82494335, 0.91094948],
       [0.2394689 , 0.32657102, 0.55139604, 0.67237777]])

In [22]:
#Return a sample (or samples) from the "standard normal" distribution.
np.random.randn(3,4)

array([[ 0.15991941,  0.73067699,  0.56301779, -0.46561939],
       [-0.06329226, -1.16679601,  0.61742874,  0.80126729],
       [ 0.74069871, -0.58788092,  0.44135222,  0.11014738]])

In [25]:
mat_rand = np.random.randint(1,6,(3,3))

In [26]:
mat_rand

array([[5, 5, 4],
       [2, 5, 1],
       [2, 1, 1]])

In [33]:
mat_rand.reshape((1,9))

array([[5, 5, 4, 2, 5, 1, 2, 1, 1]])

In [34]:
mat_rand.reshape((3,3))

array([[5, 5, 4],
       [2, 5, 1],
       [2, 1, 1]])

In [39]:
# applying conditionto the elements
arr_a = np.random.randint(0,100,(4,5))

In [40]:
arr_a

array([[19, 49, 48, 22, 53],
       [ 4, 39, 52, 20, 20],
       [28, 56, 87, 31, 81],
       [ 4, 40, 77, 66, 15]])

In [41]:
arr_a>30

array([[False,  True,  True, False,  True],
       [False,  True,  True, False, False],
       [False,  True,  True,  True,  True],
       [False,  True,  True,  True, False]])

In [42]:
arr_a[arr_a>30]

array([49, 48, 53, 39, 52, 56, 87, 31, 81, 40, 77, 66])

In [45]:
# extrancting the elements usiing index
arr_a[1,[1,2]]

array([39, 52])

In [46]:
arr_a[2,[3,4]]

array([31, 81])

In [47]:
arr_a[3,[3,4]]

array([66, 15])

In [51]:
arr_a[2:4,[3,4]]

array([[31, 81],
       [66, 15]])

In [75]:
arr_x = np.random.randint(0,12,(4,4))

In [76]:
arr_y = np.random.randint(0,3,(4,4))

In [77]:
arr_x

array([[ 8,  8,  6,  3],
       [10,  9,  5,  9],
       [ 3,  0,  9,  6],
       [ 8,  0, 10,  7]])

In [78]:
arr_y

array([[2, 1, 2, 0],
       [2, 1, 2, 0],
       [0, 2, 2, 1],
       [0, 1, 0, 1]])

In [79]:
# Element-wise additon
arr_x + arr_y

array([[10,  9,  8,  3],
       [12, 10,  7,  9],
       [ 3,  2, 11,  7],
       [ 8,  1, 10,  8]])

In [80]:
# Element-wise subtraction
arr_x - arr_y

array([[ 6,  7,  4,  3],
       [ 8,  8,  3,  9],
       [ 3, -2,  7,  5],
       [ 8, -1, 10,  6]])

In [81]:
# Element-wise multiplication
arr_x * arr_y

array([[16,  8, 12,  0],
       [20,  9, 10,  0],
       [ 0,  0, 18,  6],
       [ 0,  0,  0,  7]])

In [82]:
# Matrix multiplication
arr_x@arr_y

array([[32, 31, 44,  9],
       [38, 38, 48, 14],
       [ 6, 27, 24, 15],
       [16, 35, 36, 17]])

In [84]:
# division element wise
# Note:When divide by zero error occurs that it returns inf which stands for infinity in numpy
arr_x / arr_y

/tmp/ipykernel_70/3416354693.py:3: RuntimeWarning: divide by zero encountered in divide
  arr_x / arr_y


array([[4. , 8. , 3. , inf],
       [5. , 9. , 2.5, inf],
       [inf, 0. , 4.5, 6. ],
       [inf, 0. , inf, 7. ]])

In [86]:
# Broadcastign operations 
arr_0 =np.zeros((3,3))

In [87]:
arr_0

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [88]:
# Broadcasting addition
arr_0+1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [89]:
# Broadcasting addition of rows
l_arry = np.array([1,2,3])

arr_0+l_arry

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [91]:
# Broadcasting addition of columns
l_arry_t = np.array([[1,2,3]]).T

arr_0+l_arry_t

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [92]:
# Squareroot
np.sqrt(arr_x )

array([[2.82842712, 2.82842712, 2.44948974, 1.73205081],
       [3.16227766, 3.        , 2.23606798, 3.        ],
       [1.73205081, 0.        , 3.        , 2.44948974],
       [2.82842712, 0.        , 3.16227766, 2.64575131]])

In [93]:
np.exp(arr_x )

array([[2.98095799e+03, 2.98095799e+03, 4.03428793e+02, 2.00855369e+01],
       [2.20264658e+04, 8.10308393e+03, 1.48413159e+02, 8.10308393e+03],
       [2.00855369e+01, 1.00000000e+00, 8.10308393e+03, 4.03428793e+02],
       [2.98095799e+03, 1.00000000e+00, 2.20264658e+04, 1.09663316e+03]])

In [94]:
np.log(arr_x)

/tmp/ipykernel_70/2089750675.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr_x)


array([[2.07944154, 2.07944154, 1.79175947, 1.09861229],
       [2.30258509, 2.19722458, 1.60943791, 2.19722458],
       [1.09861229,       -inf, 2.19722458, 1.79175947],
       [2.07944154,       -inf, 2.30258509, 1.94591015]])