In [1]:
import numpy as np

In [2]:
l =list(range(10))

In [3]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
n_a = np.array(l)

In [6]:
type(n_a)

numpy.ndarray

In [7]:
np.asarray(l)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
l1 =[1,2,3]
l2 =[4,5,6]

In [26]:
arr2 = np.array([l1,l2,l2])

In [27]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [28]:
arr2.ndim

2

In [29]:
arr3 = np.array([[l1,l2,l2],[l2,l1,l2]])

In [31]:
arr3

array([[[1, 2, 3],
        [4, 5, 6],
        [4, 5, 6]],

       [[4, 5, 6],
        [1, 2, 3],
        [4, 5, 6]]])

In [32]:
arr3.ndim

3

In [37]:
# Construct an array by executing a function over each coordinate(x,y). 
np.fromfunction(lambda x,y: x == y,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [53]:
mat1 = np.fromfunction(lambda x,y: x**y,(3,3))

In [40]:
# Construct an array from iterable object
(i for i in range(10))

<generator object <genexpr> at 0x7fec169d09e0>

In [41]:
iter_obj  = (i for i in range(10))

In [42]:
np.fromiter(iter_obj,dtype='int64')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
# construct an array from string
str_list = '1;2;3;4;5;6;7'
str_arr = np.fromstring(str_list,sep=';',dtype="int64")

In [51]:
str_arr.nbytes

56

In [52]:
str_arr.size

7

In [54]:
mat1.size

9

In [55]:
mat1.shape

(3, 3)

In [56]:
mat1.ndim

2

In [58]:
mat1.dtype

dtype('float64')