In [13]:
import numpy as np

In [14]:
arr = np.random.randint(1,10,(10))

In [15]:
arr

array([7, 4, 5, 9, 8, 7, 1, 6, 2, 5])

In [16]:
# Sort, Search & Count functions
arr.sort()

In [17]:
arr

array([1, 2, 4, 5, 5, 6, 7, 7, 8, 9])

In [19]:
# Find indices where elements should be inserted to maintain order.
arr.searchsorted(3)

2

In [24]:
# Count non-sero elements
np.count_nonzero(arr)

10

In [27]:
# Search where the element exists -Returns the indcies of elements that satisfy the condition
np.where(arr >6)

(array([6, 7, 8, 9]),)

In [28]:
np.extract(arr >6,arr)

array([7, 7, 8, 9])

In [29]:
arr_3 = np.array([1,2,3,4,5,6])

In [39]:
# Numpy copies and views

# Shallow copy: pointer refers to the original arry rather than creating a new one
arr_4 = arr_3

# Shallow copy can als0 be created using
arr_v = arr_3.view()

In [40]:
arr_4[0] = 3

In [41]:
arr_4

array([3, 2, 3, 4, 5, 6])

In [42]:
arr_3

array([3, 2, 3, 4, 5, 6])

In [43]:
# Deep copy: Creates a copy
arr_5 = arr_3.copy()

In [44]:
arr_5[0]=45

In [45]:
arr_5

array([45,  2,  3,  4,  5,  6])

In [46]:
arr_3

array([3, 2, 3, 4, 5, 6])

In [47]:
# Numpy Matrix Library
import numpy.matlib as nm

In [51]:
nm.zeros((3,3))

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [54]:
nm.ones((4,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [56]:
nm.eye((3))

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])